package com.example.newspring.controllers;

import com.example.newspring.domain.Customer;
import com.example.newspring.repo.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class CustomerController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/user") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestBody Customer customer) {
        Customer n = new Customer();
        n.setName(customer.getName());
        n.setEmail(customer.getEmail());
        userRepository.save(n);
        return "Saved";
    }
}
